fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# app/config/routing.yml
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

profile:
    path:     /profile
    defaults: { _controller: AppBundle:Profile:show }

api_get_random_position:
    path: api/get/position
    defaults:
        _controller: AppBundle:Api\Position:getRandomPosition
    options:
        expose: true

api_set_position:
    path: api/set/position
    defaults:
        _controller: AppBundle:Api\Position:setPosition
    options:
        expose: true