fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
    
# app/config/routing.yml
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
